// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };


type PickContentRelationshipFieldData<
	TRelationship extends prismic.CustomTypeModelFetchCustomTypeLevel1 | prismic.CustomTypeModelFetchCustomTypeLevel2 | prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<string, prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone>,
	TLang extends string
> = |
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship["id"]]:
			ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
	} &
	// Group
	{
		[TGroup in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup["id"]]:
			TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
				? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
				: never
	} &
	// Other fields
	{
		[TFieldKey in Extract<TRelationship["fields"][number], string>]:
			TFieldKey extends keyof TData ? TData[TFieldKey] : never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[] | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string
> = {
	[ID in Exclude<TCustomType[number], string>["id"]]:
		prismic.ContentRelationshipField<
			ID,
			TLang,
			PickContentRelationshipFieldData<
				Extract<TCustomType[number], { id: ID }>,
				Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
				TLang
			>
		>
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
	/**
	 * Title field in *Blog Post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Kāpēc regulāra mutes higiēna ir labākā investīcija?
	 * - **API ID Path**: blog_post.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Category field in *Blog Post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: MUTES HIGIĒNA
	 * - **API ID Path**: blog_post.category
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	category: prismic.KeyTextField;
	
	/**
	 * Short Summary Description field in *Blog Post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Brief description...
	 * - **API ID Path**: blog_post.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * Detailed Article Content field in *Blog Post*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Full paragraphs of the blog post...
	 * - **API ID Path**: blog_post.detailedContent
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	detailedContent: prismic.RichTextField;
	
	/**
	 * Cover Image field in *Blog Post*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * Publication Date String field in *Blog Post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 18. Maijs, 2026
	 * - **API ID Path**: blog_post.date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	date: prismic.KeyTextField;
	
	/**
	 * Author Name field in *Blog Post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Dr. Līga Ozoliņa
	 * - **API ID Path**: blog_post.author
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	author: prismic.KeyTextField;
	
	/**
	 * Reading Time field in *Blog Post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 4 MIN
	 * - **API ID Path**: blog_post.readTime
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	readTime: prismic.KeyTextField;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<BlogPostDocumentData>, "blog_post", Lang>;

/**
 * Item in *Doctor → Specializations*
 */
export interface DoctorDocumentDataSpecializationsItem {
	/**
	 * Specialization Item field in *Doctor → Specializations*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: doctor.specializations[].item
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	item: prismic.KeyTextField;
}

/**
 * Item in *Doctor → Education & Courses*
 */
export interface DoctorDocumentDataEducationItem {
	/**
	 * Education Item field in *Doctor → Education & Courses*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: doctor.education[].item
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	item: prismic.KeyTextField;
}

/**
 * Item in *Doctor → Spoken Languages*
 */
export interface DoctorDocumentDataLanguagesItem {
	/**
	 * Language field in *Doctor → Spoken Languages*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: *None*
	 * - **API ID Path**: doctor.languages[].item
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	item: prismic.KeyTextField;
}

/**
 * Content for Doctor documents
 */
interface DoctorDocumentData {
	/**
	 * Name field in *Doctor*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Dr. Anna Bērziņa
	 * - **API ID Path**: doctor.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * Category field in *Doctor*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: SPECIĀLISTE or ĶIRURGS
	 * - **API ID Path**: doctor.category
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	category: prismic.KeyTextField;
	
	/**
	 * Role field in *Doctor*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: ZOBĀRSTE
	 * - **API ID Path**: doctor.role
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	role: prismic.KeyTextField;
	
	/**
	 * Short Description field in *Doctor*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Short summary of the doctor...
	 * - **API ID Path**: doctor.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * Full Biography field in *Doctor*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Long professional bio for the detail modal...
	 * - **API ID Path**: doctor.fullBio
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	fullBio: prismic.RichTextField;
	
	/**
	 * Photo field in *Doctor*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: doctor.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * Specializations field in *Doctor*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: doctor.specializations[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	specializations: prismic.GroupField<Simplify<DoctorDocumentDataSpecializationsItem>>;
	
	/**
	 * Education & Courses field in *Doctor*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: doctor.education[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	education: prismic.GroupField<Simplify<DoctorDocumentDataEducationItem>>;
	
	/**
	 * Spoken Languages field in *Doctor*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: doctor.languages[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	languages: prismic.GroupField<Simplify<DoctorDocumentDataLanguagesItem>>;
}

/**
 * Doctor document from Prismic
 *
 * - **API ID**: `doctor`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type DoctorDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<DoctorDocumentData>, "doctor", Lang>;

/**
 * Item in *Footer → Clinics*
 */
export interface FooterDocumentDataClinicsItem {
	/**
	 * Clinic Name field in *Footer → Clinics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Dentamic Rīga
	 * - **API ID Path**: footer.clinics[].name
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * Address field in *Footer → Clinics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Brīvības iela 100, Rīga, LV-1001
	 * - **API ID Path**: footer.clinics[].address
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	address: prismic.KeyTextField;
	
	/**
	 * Phone Number field in *Footer → Clinics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: +371 29 459 999
	 * - **API ID Path**: footer.clinics[].phone
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	phone: prismic.KeyTextField;
	
	/**
	 * Email Address field in *Footer → Clinics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: riga@dentamic.lv
	 * - **API ID Path**: footer.clinics[].email
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	email: prismic.KeyTextField;
	
	/**
	 * Working Hours Weekdays field in *Footer → Clinics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: P. - Pk.: 09:00 - 19:00
	 * - **API ID Path**: footer.clinics[].work_hours_weekdays
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	work_hours_weekdays: prismic.KeyTextField;
	
	/**
	 * Working Hours Saturday field in *Footer → Clinics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: S.: 10:00 - 15:00
	 * - **API ID Path**: footer.clinics[].work_hours_saturday
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	work_hours_saturday: prismic.KeyTextField;
	
	/**
	 * Working Hours Sunday field in *Footer → Clinics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Sv.: Slēgts
	 * - **API ID Path**: footer.clinics[].work_hours_sunday
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	work_hours_sunday: prismic.KeyTextField;
	
	/**
	 * Weekdays Label field in *Footer → Clinics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Darba dienas:
	 * - **API ID Path**: footer.clinics[].label_weekdays
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label_weekdays: prismic.KeyTextField;
	
	/**
	 * Saturday Label field in *Footer → Clinics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Sestdiena:
	 * - **API ID Path**: footer.clinics[].label_saturday
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label_saturday: prismic.KeyTextField;
	
	/**
	 * Sunday Label field in *Footer → Clinics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Svētdiena:
	 * - **API ID Path**: footer.clinics[].label_sunday
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label_sunday: prismic.KeyTextField;
	
	/**
	 * Accessibility Alert Message field in *Footer → Clinics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: e.g., Klīnika ir pilnībā pieejama ratiņkrēslā
	 * - **API ID Path**: footer.clinics[].accessibility_alert
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	accessibility_alert: prismic.KeyTextField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
	/**
	 * Logo Text field in *Footer*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Dentamic
	 * - **API ID Path**: footer.logo_text
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	logo_text: prismic.KeyTextField;
	
	/**
	 * Logo Image field in *Footer*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.logo_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logo_image: prismic.ImageField<never>;
	
	/**
	 * Description field in *Footer*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Modern dental technologies...
	 * - **API ID Path**: footer.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * Clinics Column Title field in *Footer*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Mūsu Klīnikas
	 * - **API ID Path**: footer.clinics_column_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	clinics_column_title: prismic.KeyTextField;
	
	/**
	 * Working Hours Column Title field in *Footer*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Darba Laiks
	 * - **API ID Path**: footer.working_hours_column_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	working_hours_column_title: prismic.KeyTextField;
	
	/**
	 * Clinics field in *Footer*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.clinics[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	clinics: prismic.GroupField<Simplify<FooterDocumentDataClinicsItem>>;
	
	/**
	 * Copyright Text field in *Footer*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Dentamic. Visas tiesības aizsargātas.
	 * - **API ID Path**: footer.copyright_text
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	copyright_text: prismic.KeyTextField;
	
	/**
	 * Privacy Policy Label field in *Footer*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Privātuma politika
	 * - **API ID Path**: footer.privacy_policy_label
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	privacy_policy_label: prismic.KeyTextField;
	
	/**
	 * Privacy Policy Link field in *Footer*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Select Privacy Policy page or URL
	 * - **API ID Path**: footer.privacy_policy_link
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	privacy_policy_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Cookie Policy Label field in *Footer*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Sīkdatņu politika
	 * - **API ID Path**: footer.cookie_policy_label
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cookie_policy_label: prismic.KeyTextField;
	
	/**
	 * Cookie Policy Link field in *Footer*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Select Cookie Policy page or URL
	 * - **API ID Path**: footer.cookie_policy_link
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cookie_policy_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<FooterDocumentData>, "footer", Lang>;

type HomepageDocumentDataSlicesSlice = HeroSlice | ServicesListSlice | DoctorsListSlice | PricelistSlice | TestimonialsListSlice | ContactFormSlice | CtaBlockSlice | CeoBlockSlice | TestimonialBlockSlice

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
	/**
	 * Slice Zone field in *Homepage*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<HomepageDocumentData>, "homepage", Lang>;

/**
 * Item in *Menu → Menu Links*
 */
export interface MenuDocumentDataMenuLinksItem {
	/**
	 * Label field in *Menu → Menu Links*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Pakalpojumi
	 * - **API ID Path**: menu.menu_links[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * Path/UID field in *Menu → Menu Links*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: services
	 * - **API ID Path**: menu.menu_links[].path
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	path: prismic.KeyTextField;
}

/**
 * Content for Menu documents
 */
interface MenuDocumentData {
	/**
	 * Logo Text field in *Menu*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Dentamic
	 * - **API ID Path**: menu.logo_text
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	logo_text: prismic.KeyTextField;
	
	/**
	 * Header logo field in *Menu*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menu.logo_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logo_image: prismic.ImageField<never>;
	
	/**
	 * Phone Number field in *Menu*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: +371 20000000
	 * - **API ID Path**: menu.phone_number
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	phone_number: prismic.KeyTextField;
	
	/**
	 * Booking Button Text field in *Menu*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Pierakstīties
	 * - **API ID Path**: menu.booking_button_text
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	booking_button_text: prismic.KeyTextField;
	
	/**
	 * Menu Links field in *Menu*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menu.menu_links[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	menu_links: prismic.GroupField<Simplify<MenuDocumentDataMenuLinksItem>>;
}

/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;

type PageDocumentDataSlicesSlice = HeroSlice | ServicesListSlice | DoctorsListSlice | PricelistSlice | TestimonialsListSlice | ContactFormSlice | CtaBlockSlice | CeoBlockSlice | TestimonialBlockSlice

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Page Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Services, Testimonials, etc.
	 * - **API ID Path**: page.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Price Item documents
 */
interface PriceItemDocumentData {
	/**
	 * Category field in *Price Item*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Higiēna un profilakse
	 * - **API ID Path**: price_item.category
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	category: prismic.SelectField<"Higiēna un profilakse" | "Zobu implantācija un ķirurģija" | "Terapeitiskā zobārstniecība (plombēšana)" | "Estētiskā zobārstniecība un protezēšana" | "Ortodontija (kapes & breketes)", "filled">;
	
	/**
	 * Price Item Name field in *Price Item*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Profesionālā mutes dobuma higiēna
	 * - **API ID Path**: price_item.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * Price Value field in *Price Item*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 85 €
	 * - **API ID Path**: price_item.price
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	price: prismic.KeyTextField;
	
	/**
	 * Item Note / Subtitle field in *Price Item*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Ultrasonic scaler, air-flow...
	 * - **API ID Path**: price_item.note
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	note: prismic.KeyTextField;
	
	/**
	 * Display Order Index field in *Price Item*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: 1
	 * - **API ID Path**: price_item.order
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	order: prismic.NumberField;
}

/**
 * Price Item document from Prismic
 *
 * - **API ID**: `price_item`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PriceItemDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<PriceItemDocumentData>, "price_item", Lang>;

/**
 * Content for Service documents
 */
interface ServiceDocumentData {
	/**
	 * Title field in *Service*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Terapeitiskā zobārstniecība
	 * - **API ID Path**: service.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Short Description field in *Service*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Brief service summary...
	 * - **API ID Path**: service.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * Detailed Info field in *Service*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Long descriptive paragraph of the service...
	 * - **API ID Path**: service.detailedInfo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	detailedInfo: prismic.RichTextField;
	
	/**
	 * Price Range field in *Service*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: no 60 €
	 * - **API ID Path**: service.priceRange
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	priceRange: prismic.KeyTextField;
	
	/**
	 * Duration field in *Service*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 30 - 60 min
	 * - **API ID Path**: service.duration
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	duration: prismic.KeyTextField;
	
	/**
	 * Icon Name (Lucide) field in *Service*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: ShieldCheck, Sparkles, Droplet, Scissors, Activity
	 * - **API ID Path**: service.iconName
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	iconName: prismic.KeyTextField;
	
	/**
	 * Service Image field in *Service*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Service document from Prismic
 *
 * - **API ID**: `service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<ServiceDocumentData>, "service", Lang>;

/**
 * Content for Testimonial documents
 */
interface TestimonialDocumentData {
	/**
	 * Author Name field in *Testimonial*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Kristaps Zariņš
	 * - **API ID Path**: testimonial.author
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	author: prismic.KeyTextField;
	
	/**
	 * Initials field in *Testimonial*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: KZ
	 * - **API ID Path**: testimonial.initials
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	initials: prismic.KeyTextField;
	
	/**
	 * Background Color Class field in *Testimonial*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: bg-[#511B29] text-white
	 * - **API ID Path**: testimonial.bgColor
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	bgColor: prismic.KeyTextField;
	
	/**
	 * Treatment Received field in *Testimonial*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Zobu implantācija (Straumann)
	 * - **API ID Path**: testimonial.treatment
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	treatment: prismic.KeyTextField;
	
	/**
	 * Doctor Name field in *Testimonial*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Dr. Jānis Kalniņš
	 * - **API ID Path**: testimonial.doctor
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	doctor: prismic.KeyTextField;
	
	/**
	 * Rating (1-5) field in *Testimonial*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: 5
	 * - **API ID Path**: testimonial.rating
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	rating: prismic.NumberField;
	
	/**
	 * Date String field in *Testimonial*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 12.04.2026
	 * - **API ID Path**: testimonial.date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	date: prismic.KeyTextField;
	
	/**
	 * Advantage Tag field in *Testimonial*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Premium kvalitāte
	 * - **API ID Path**: testimonial.advTag
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	advTag: prismic.KeyTextField;
	
	/**
	 * Short Quote Summary field in *Testimonial*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Painless Swiss implants...
	 * - **API ID Path**: testimonial.quote
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	quote: prismic.KeyTextField;
	
	/**
	 * Full Experience Story field in *Testimonial*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Full story detailed description...
	 * - **API ID Path**: testimonial.story
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	story: prismic.KeyTextField;
}

/**
 * Testimonial document from Prismic
 *
 * - **API ID**: `testimonial`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<TestimonialDocumentData>, "testimonial", Lang>;

export type AllDocumentTypes = BlogPostDocument | DoctorDocument | FooterDocument | HomepageDocument | MenuDocument | PageDocument | PriceItemDocument | ServiceDocument | TestimonialDocument;

/**
 * Primary content in *CEOBlock → Default → Primary*
 */
export interface CeoBlockSliceDefaultPrimary {
	/**
	 * Leader Tag field in *CEOBlock → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Klīnikas vadītājs un vadošais speciālists
	 * - **API ID Path**: ceo_block.default.primary.leader_tag
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	leader_tag: prismic.KeyTextField;
	
	/**
	 * Name field in *CEOBlock → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Dr. Jānis Bērziņš
	 * - **API ID Path**: ceo_block.default.primary.name
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * Biography field in *CEOBlock → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Mūsu klīnikas filozofija balstās uz...
	 * - **API ID Path**: ceo_block.default.primary.biography
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	biography: prismic.RichTextField;
	
	/**
	 * Image field in *CEOBlock → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ceo_block.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * Signature Image field in *CEOBlock → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ceo_block.default.primary.signature_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	signature_image: prismic.ImageField<never>;
	
	/**
	 * Link Text field in *CEOBlock → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Uzzināt vairāk
	 * - **API ID Path**: ceo_block.default.primary.link_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	link_text: prismic.KeyTextField;
	
	/**
	 * Link URL field in *CEOBlock → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Select page or enter URL
	 * - **API ID Path**: ceo_block.default.primary.link_url
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link_url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for CEOBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CeoBlockSliceDefault = prismic.SharedSliceVariation<"default", Simplify<CeoBlockSliceDefaultPrimary>, never>;

/**
 * Slice variation for *CEOBlock*
 */
type CeoBlockSliceVariation = CeoBlockSliceDefault

/**
 * CEOBlock Shared Slice
 *
 * - **API ID**: `ceo_block`
 * - **Description**: Renders the CEO/Clinic Director card block with bio, photo, signature, and learn more link.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CeoBlockSlice = prismic.SharedSlice<"ceo_block", CeoBlockSliceVariation>;

/**
 * Primary content in *ContactForm → Default → Primary*
 */
export interface ContactFormSliceDefaultPrimary {
	/**
	 * Title field in *ContactForm → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Mūsu klīnikas un kontakti
	 * - **API ID Path**: contact_form.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Subtitle field in *ContactForm → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Būsim priecīgi Jūs redzēt...
	 * - **API ID Path**: contact_form.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	subtitle: prismic.KeyTextField;
}

/**
 * Default variation for ContactForm Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactFormSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ContactFormSliceDefaultPrimary>, never>;

/**
 * Slice variation for *ContactForm*
 */
type ContactFormSliceVariation = ContactFormSliceDefault

/**
 * ContactForm Shared Slice
 *
 * - **API ID**: `contact_form`
 * - **Description**: Renders clinic locations, details, and the appointment booking contact form.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactFormSlice = prismic.SharedSlice<"contact_form", ContactFormSliceVariation>;

/**
 * Primary content in *CTABlock → Default → Primary*
 */
export interface CtaBlockSliceDefaultPrimary {
	/**
	 * Badge text field in *CTABlock → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Share Your Experience
	 * - **API ID Path**: cta_block.default.primary.badge_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	badge_text: prismic.KeyTextField;
	
	/**
	 * Title field in *CTABlock → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Would you like to leave a review of your visit?
	 * - **API ID Path**: cta_block.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Description field in *CTABlock → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Every patient's opinion helps us grow...
	 * - **API ID Path**: cta_block.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * Button text field in *CTABlock → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Book a Visit
	 * - **API ID Path**: cta_block.default.primary.button_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	button_text: prismic.KeyTextField;
	
	/**
	 * Button Link field in *CTABlock → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Select page or enter URL
	 * - **API ID Path**: cta_block.default.primary.button_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	button_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Background Color field in *CTABlock → Default → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta_block.default.primary.background_color
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	background_color: prismic.ColorField;
}

/**
 * Default variation for CTABlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaBlockSliceDefault = prismic.SharedSliceVariation<"default", Simplify<CtaBlockSliceDefaultPrimary>, never>;

/**
 * Slice variation for *CTABlock*
 */
type CtaBlockSliceVariation = CtaBlockSliceDefault

/**
 * CTABlock Shared Slice
 *
 * - **API ID**: `cta_block`
 * - **Description**: CTA block with badge, title, description, and button link fields
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaBlockSlice = prismic.SharedSlice<"cta_block", CtaBlockSliceVariation>;

/**
 * Primary content in *DoctorsList → Default → Primary*
 */
export interface DoctorsListSliceDefaultPrimary {
	/**
	 * Title field in *DoctorsList → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Mūsu komanda
	 * - **API ID Path**: doctors_list.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Subtitle field in *DoctorsList → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Profesionāli speciālisti...
	 * - **API ID Path**: doctors_list.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	subtitle: prismic.KeyTextField;
}

/**
 * Default variation for DoctorsList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DoctorsListSliceDefault = prismic.SharedSliceVariation<"default", Simplify<DoctorsListSliceDefaultPrimary>, never>;

/**
 * Slice variation for *DoctorsList*
 */
type DoctorsListSliceVariation = DoctorsListSliceDefault

/**
 * DoctorsList Shared Slice
 *
 * - **API ID**: `doctors_list`
 * - **Description**: Renders the dentist profiles cards grid.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DoctorsListSlice = prismic.SharedSlice<"doctors_list", DoctorsListSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Title field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Izcila zobārstniecība Jūsu labsajūtai
	 * - **API ID Path**: hero.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Subtitle field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Modernas tehnoloģijas un individuāla pieeja...
	 * - **API ID Path**: hero.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	subtitle: prismic.RichTextField;
	
	/**
	 * Premium tag text field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Premium Care
	 * - **API ID Path**: hero.default.primary.premium_tag
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	premium_tag: prismic.KeyTextField;
	
	/**
	 * Primary CTA text field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Pierakstīties vizītei
	 * - **API ID Path**: hero.default.primary.cta_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_text: prismic.KeyTextField;
	
	/**
	 * Primary CTA Link field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Select page or enter URL
	 * - **API ID Path**: hero.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Secondary CTA text field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Mūsu pakalpojumi
	 * - **API ID Path**: hero.default.primary.secondary_cta_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	secondary_cta_text: prismic.KeyTextField;
	
	/**
	 * Secondary CTA Link field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Select page or enter URL
	 * - **API ID Path**: hero.default.primary.secondary_cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	secondary_cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Background Image field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.background_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	background_image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero default section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<"default", Simplify<HeroSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero section with title, subtitle, and CTA buttons
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *Pricelist → Default → Primary*
 */
export interface PricelistSliceDefaultPrimary {
	/**
	 * Title field in *Pricelist → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Caurspīdīgas cenas un kvalitāte
	 * - **API ID Path**: pricelist.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Subtitle field in *Pricelist → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Skaidrs un saprotams cenrādis...
	 * - **API ID Path**: pricelist.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	subtitle: prismic.KeyTextField;
}

/**
 * Default variation for Pricelist Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PricelistSliceDefault = prismic.SharedSliceVariation<"default", Simplify<PricelistSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Pricelist*
 */
type PricelistSliceVariation = PricelistSliceDefault

/**
 * Pricelist Shared Slice
 *
 * - **API ID**: `pricelist`
 * - **Description**: Renders the price categories and price lists tables.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PricelistSlice = prismic.SharedSlice<"pricelist", PricelistSliceVariation>;

/**
 * Primary content in *ServicesList → Default → Primary*
 */
export interface ServicesListSliceDefaultPrimary {
	/**
	 * Title field in *ServicesList → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Augstākās klases zobārstniecība
	 * - **API ID Path**: services_list.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Subtitle field in *ServicesList → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Pilns mūsdienīgu pakalpojumu spektrs...
	 * - **API ID Path**: services_list.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	subtitle: prismic.KeyTextField;
}

/**
 * Default variation for ServicesList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesListSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ServicesListSliceDefaultPrimary>, never>;

/**
 * Slice variation for *ServicesList*
 */
type ServicesListSliceVariation = ServicesListSliceDefault

/**
 * ServicesList Shared Slice
 *
 * - **API ID**: `services_list`
 * - **Description**: Renders the dynamic cards list of all dental services.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicesListSlice = prismic.SharedSlice<"services_list", ServicesListSliceVariation>;

/**
 * Primary content in *TestimonialBlock → Default → Primary*
 */
export interface TestimonialBlockSliceDefaultPrimary {
	/**
	 * Badge Text field in *TestimonialBlock → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Pacientu atsauksmes
	 * - **API ID Path**: testimonial_block.default.primary.badge_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	badge_text: prismic.KeyTextField;
	
	/**
	 * Title field in *TestimonialBlock → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Atsauksmes
	 * - **API ID Path**: testimonial_block.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Subtitle field in *TestimonialBlock → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Mūsu pacienti novērtē...
	 * - **API ID Path**: testimonial_block.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	subtitle: prismic.KeyTextField;
	
	/**
	 * Section Link Text field in *TestimonialBlock → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Skatīt visus pacientu stāstus
	 * - **API ID Path**: testimonial_block.default.primary.link_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	link_text: prismic.KeyTextField;
	
	/**
	 * Section Link URL field in *TestimonialBlock → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Select page or enter URL
	 * - **API ID Path**: testimonial_block.default.primary.link_url
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link_url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *TestimonialBlock → Items*
 */
export interface TestimonialBlockSliceDefaultItem {
	/**
	 * Testimonial Tagline / Treatment field in *TestimonialBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Zobu implantācija
	 * - **API ID Path**: testimonial_block.items[].tagline
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	tagline: prismic.KeyTextField;
	
	/**
	 * Author field in *TestimonialBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Anna Bērziņa
	 * - **API ID Path**: testimonial_block.items[].author
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	author: prismic.KeyTextField;
	
	/**
	 * Testimonial Text / Story field in *TestimonialBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Lieliska attieksme un nesāpīga procedūra...
	 * - **API ID Path**: testimonial_block.items[].testimonial_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	testimonial_text: prismic.KeyTextField;
	
	/**
	 * Date field in *TestimonialBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 12. Maijs, 2026
	 * - **API ID Path**: testimonial_block.items[].date
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	date: prismic.KeyTextField;
	
	/**
	 * Rating (1-5) field in *TestimonialBlock → Items*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: 5
	 * - **API ID Path**: testimonial_block.items[].rating
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	rating: prismic.NumberField;
}

/**
 * Default variation for TestimonialBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialBlockSliceDefault = prismic.SharedSliceVariation<"default", Simplify<TestimonialBlockSliceDefaultPrimary>, Simplify<TestimonialBlockSliceDefaultItem>>;

/**
 * Slice variation for *TestimonialBlock*
 */
type TestimonialBlockSliceVariation = TestimonialBlockSliceDefault

/**
 * TestimonialBlock Shared Slice
 *
 * - **API ID**: `testimonial_block`
 * - **Description**: Renders testimonial cards in a 3-column bento-like grid with editable fields and customizable CTA links.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialBlockSlice = prismic.SharedSlice<"testimonial_block", TestimonialBlockSliceVariation>;

/**
 * Primary content in *TestimonialsList → Default → Primary*
 */
export interface TestimonialsListSliceDefaultPrimary {
	/**
	 * Title field in *TestimonialsList → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Pacientu atsauksmes
	 * - **API ID Path**: testimonials_list.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Subtitle field in *TestimonialsList → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Mūsu pacienti novērtē augstāko aprūpes kvalitāti...
	 * - **API ID Path**: testimonials_list.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	subtitle: prismic.KeyTextField;
}

/**
 * Default variation for TestimonialsList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsListSliceDefault = prismic.SharedSliceVariation<"default", Simplify<TestimonialsListSliceDefaultPrimary>, never>;

/**
 * Slice variation for *TestimonialsList*
 */
type TestimonialsListSliceVariation = TestimonialsListSliceDefault

/**
 * TestimonialsList Shared Slice
 *
 * - **API ID**: `testimonials_list`
 * - **Description**: Renders the testimonials feedback cards grid.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialsListSlice = prismic.SharedSlice<"testimonials_list", TestimonialsListSliceVariation>;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
	}
	
	interface CreateWriteClient {
		(repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
	}
	
	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			BlogPostDocument,
			BlogPostDocumentData,
			DoctorDocument,
			DoctorDocumentData,
			DoctorDocumentDataSpecializationsItem,
			DoctorDocumentDataEducationItem,
			DoctorDocumentDataLanguagesItem,
			FooterDocument,
			FooterDocumentData,
			FooterDocumentDataClinicsItem,
			HomepageDocument,
			HomepageDocumentData,
			HomepageDocumentDataSlicesSlice,
			MenuDocument,
			MenuDocumentData,
			MenuDocumentDataMenuLinksItem,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			PriceItemDocument,
			PriceItemDocumentData,
			ServiceDocument,
			ServiceDocumentData,
			TestimonialDocument,
			TestimonialDocumentData,
			AllDocumentTypes,
			CeoBlockSlice,
			CeoBlockSliceDefaultPrimary,
			CeoBlockSliceVariation,
			CeoBlockSliceDefault,
			ContactFormSlice,
			ContactFormSliceDefaultPrimary,
			ContactFormSliceVariation,
			ContactFormSliceDefault,
			CtaBlockSlice,
			CtaBlockSliceDefaultPrimary,
			CtaBlockSliceVariation,
			CtaBlockSliceDefault,
			DoctorsListSlice,
			DoctorsListSliceDefaultPrimary,
			DoctorsListSliceVariation,
			DoctorsListSliceDefault,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			PricelistSlice,
			PricelistSliceDefaultPrimary,
			PricelistSliceVariation,
			PricelistSliceDefault,
			ServicesListSlice,
			ServicesListSliceDefaultPrimary,
			ServicesListSliceVariation,
			ServicesListSliceDefault,
			TestimonialBlockSlice,
			TestimonialBlockSliceDefaultPrimary,
			TestimonialBlockSliceDefaultItem,
			TestimonialBlockSliceVariation,
			TestimonialBlockSliceDefault,
			TestimonialsListSlice,
			TestimonialsListSliceDefaultPrimary,
			TestimonialsListSliceVariation,
			TestimonialsListSliceDefault
		}
	}
}