// Code generated by prismic-ts-codegen. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };


type PickContentRelationshipFieldData<
	TRelationship extends prismic.CustomTypeModelFetchCustomTypeLevel1 | prismic.CustomTypeModelFetchCustomTypeLevel2 | prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2,
	TData extends Record<string, prismic.AnyRegularField | prismic.GroupField | prismic.NestedGroupField | prismic.SliceZone>,
	TLang extends string
> = |
	// Content relationship fields
	{
		[TSubRelationship in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchContentRelationshipLevel1
		> as TSubRelationship["id"]]:
			ContentRelationshipFieldWithData<TSubRelationship["customtypes"], TLang>;
	} &
	// Group
	{
		[TGroup in Extract<
			TRelationship["fields"][number], prismic.CustomTypeModelFetchGroupLevel1 | prismic.CustomTypeModelFetchGroupLevel2
		> as TGroup["id"]]:
			TData[TGroup["id"]] extends prismic.GroupField<infer TGroupData>
				? prismic.GroupField<PickContentRelationshipFieldData<TGroup, TGroupData, TLang>>
				: never
	} &
	// Other fields
	{
		[TFieldKey in Extract<TRelationship["fields"][number], string>]:
			TFieldKey extends keyof TData ? TData[TFieldKey] : never;
	};

type ContentRelationshipFieldWithData<
	TCustomType extends readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[] | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
	TLang extends string = string
> = {
	[ID in Exclude<TCustomType[number], string>["id"]]:
		prismic.ContentRelationshipField<
			ID,
			TLang,
			PickContentRelationshipFieldData<
				Extract<TCustomType[number], { id: ID }>,
				Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
				TLang
			>
		>
}[Exclude<TCustomType[number], string>["id"]];

/**
 * Content for Blog Post documents
 */
interface BlogPostDocumentData {
	/**
	 * Title field in *Blog Post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Kāpēc regulāra mutes higiēna ir labākā investīcija?
	 * - **API ID Path**: blog_post.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Category field in *Blog Post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: MUTES HIGIĒNA
	 * - **API ID Path**: blog_post.category
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	category: prismic.KeyTextField;
	
	/**
	 * Short Summary Description field in *Blog Post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Brief description...
	 * - **API ID Path**: blog_post.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * Detailed Article Content field in *Blog Post*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Full paragraphs of the blog post...
	 * - **API ID Path**: blog_post.detailedContent
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	detailedContent: prismic.RichTextField;
	
	/**
	 * Cover Image field in *Blog Post*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_post.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * Publication Date String field in *Blog Post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 18. Maijs, 2026
	 * - **API ID Path**: blog_post.date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	date: prismic.KeyTextField;
	
	/**
	 * Author Name field in *Blog Post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Dr. Līga Ozoliņa
	 * - **API ID Path**: blog_post.author
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	author: prismic.KeyTextField;
	
	/**
	 * Reading Time field in *Blog Post*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 4 MIN
	 * - **API ID Path**: blog_post.readTime
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	readTime: prismic.KeyTextField;
}

/**
 * Blog Post document from Prismic
 *
 * - **API ID**: `blog_post`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BlogPostDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<BlogPostDocumentData>, "blog_post", Lang>;

/**
 * Item in *Footer → Clinics*
 */
export interface FooterDocumentDataClinicsItem {
	/**
	 * Clinic Name field in *Footer → Clinics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Dentamic Rīga
	 * - **API ID Path**: footer.clinics[].name
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * Address field in *Footer → Clinics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Brīvības iela 100, Rīga, LV-1001
	 * - **API ID Path**: footer.clinics[].address
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	address: prismic.KeyTextField;
	
	/**
	 * Phone Number field in *Footer → Clinics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: +371 29 459 999
	 * - **API ID Path**: footer.clinics[].phone
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	phone: prismic.KeyTextField;
	
	/**
	 * Email Address field in *Footer → Clinics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: riga@dentamic.lv
	 * - **API ID Path**: footer.clinics[].email
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	email: prismic.KeyTextField;
	
	/**
	 * Working Hours Weekdays field in *Footer → Clinics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: P. - Pk.: 09:00 - 19:00
	 * - **API ID Path**: footer.clinics[].work_hours_weekdays
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	work_hours_weekdays: prismic.KeyTextField;
	
	/**
	 * Working Hours Saturday field in *Footer → Clinics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: S.: 10:00 - 15:00
	 * - **API ID Path**: footer.clinics[].work_hours_saturday
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	work_hours_saturday: prismic.KeyTextField;
	
	/**
	 * Working Hours Sunday field in *Footer → Clinics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Sv.: Slēgts
	 * - **API ID Path**: footer.clinics[].work_hours_sunday
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	work_hours_sunday: prismic.KeyTextField;
	
	/**
	 * Weekdays Label field in *Footer → Clinics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Darba dienas:
	 * - **API ID Path**: footer.clinics[].label_weekdays
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label_weekdays: prismic.KeyTextField;
	
	/**
	 * Saturday Label field in *Footer → Clinics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Sestdiena:
	 * - **API ID Path**: footer.clinics[].label_saturday
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label_saturday: prismic.KeyTextField;
	
	/**
	 * Sunday Label field in *Footer → Clinics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Svētdiena:
	 * - **API ID Path**: footer.clinics[].label_sunday
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label_sunday: prismic.KeyTextField;
	
	/**
	 * Accessibility Alert Message field in *Footer → Clinics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: e.g., Klīnika ir pilnībā pieejama ratiņkrēslā
	 * - **API ID Path**: footer.clinics[].accessibility_alert
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	accessibility_alert: prismic.KeyTextField;
	
	/**
	 * Map Link Title field in *Footer → Clinics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Karte / Google Maps
	 * - **API ID Path**: footer.clinics[].map_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	map_title: prismic.KeyTextField;
	
	/**
	 * Map Link URL field in *Footer → Clinics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: https://maps.app.goo.gl/...
	 * - **API ID Path**: footer.clinics[].map_url
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	map_url: prismic.KeyTextField;
	
	/**
	 * Waze Link Title field in *Footer → Clinics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Waze
	 * - **API ID Path**: footer.clinics[].waze_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	waze_title: prismic.KeyTextField;
	
	/**
	 * Waze Link URL field in *Footer → Clinics*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: https://waze.com/ul/hud1k9wgd7
	 * - **API ID Path**: footer.clinics[].waze_url
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	waze_url: prismic.KeyTextField;
}

/**
 * Content for Footer documents
 */
interface FooterDocumentData {
	/**
	 * Logo Text field in *Footer*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Dentamic
	 * - **API ID Path**: footer.logo_text
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	logo_text: prismic.KeyTextField;
	
	/**
	 * Logo Image field in *Footer*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.logo_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logo_image: prismic.ImageField<never>;
	
	/**
	 * Description field in *Footer*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Modern dental technologies...
	 * - **API ID Path**: footer.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * Clinics Column Title field in *Footer*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Mūsu Klīnikas
	 * - **API ID Path**: footer.clinics_column_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	clinics_column_title: prismic.KeyTextField;
	
	/**
	 * Working Hours Column Title field in *Footer*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Darba Laiks
	 * - **API ID Path**: footer.working_hours_column_title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	working_hours_column_title: prismic.KeyTextField;
	
	/**
	 * Clinics field in *Footer*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: footer.clinics[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	clinics: prismic.GroupField<Simplify<FooterDocumentDataClinicsItem>>;
	
	/**
	 * Copyright Text field in *Footer*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Dentamic. Visas tiesības aizsargātas.
	 * - **API ID Path**: footer.copyright_text
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	copyright_text: prismic.KeyTextField;
	
	/**
	 * Privacy Policy Label field in *Footer*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Privātuma politika
	 * - **API ID Path**: footer.privacy_policy_label
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	privacy_policy_label: prismic.KeyTextField;
	
	/**
	 * Privacy Policy Link field in *Footer*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Select Privacy Policy page or URL
	 * - **API ID Path**: footer.privacy_policy_link
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	privacy_policy_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Cookie Policy Label field in *Footer*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Sīkdatņu politika
	 * - **API ID Path**: footer.cookie_policy_label
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cookie_policy_label: prismic.KeyTextField;
	
	/**
	 * Cookie Policy Link field in *Footer*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Select Cookie Policy page or URL
	 * - **API ID Path**: footer.cookie_policy_link
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cookie_policy_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Footer document from Prismic
 *
 * - **API ID**: `footer`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type FooterDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<FooterDocumentData>, "footer", Lang>;

type HomepageDocumentDataSlicesSlice = HeroSlice | ServiceGridSlice | ServicePageSlice | DoctorBlockSlice | PricelistSlice | TestimonialGridSlice | ContactBlockSlice | CtaBlockSlice | CeoBlockSlice | TestimonialBlockSlice | PartnerBlockSlice | PageTitleSlice | BlogGridSlice | BlogPageSlice | DoctorGridSlice

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
	/**
	 * Slice Zone field in *Homepage*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;

	/**
	 * SEO Title field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Enter page title for search engines
	 * - **API ID Path**: homepage.meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;

	/**
	 * SEO Description field in *Homepage*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Enter page description for search engines
	 * - **API ID Path**: homepage.meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Schema.org Image field in *Homepage*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.schema_image
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	schema_image: prismic.ImageField<never>;

	/**
	 * Social Share Image (OpenGraph/Twitter) field in *Homepage*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: homepage.og_image
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	og_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<HomepageDocumentData>, "homepage", Lang>;

/**
 * Item in *Menu → Menu Links*
 */
export interface MenuDocumentDataMenuLinksItem {
	/**
	 * Label field in *Menu → Menu Links*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Pakalpojumi
	 * - **API ID Path**: menu.menu_links[].label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	label: prismic.KeyTextField;
	
	/**
	 * Path/UID field in *Menu → Menu Links*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: services
	 * - **API ID Path**: menu.menu_links[].path
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	path: prismic.KeyTextField;
}

/**
 * Content for Menu documents
 */
interface MenuDocumentData {
	/**
	 * Logo Text field in *Menu*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Dentamic
	 * - **API ID Path**: menu.logo_text
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	logo_text: prismic.KeyTextField;
	
	/**
	 * Header logo field in *Menu*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menu.logo_image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logo_image: prismic.ImageField<never>;
	
	/**
	 * Phone Number field in *Menu*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: +371 20000000
	 * - **API ID Path**: menu.phone_number
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	phone_number: prismic.KeyTextField;
	
	/**
	 * Booking Button Text field in *Menu*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Pierakstīties
	 * - **API ID Path**: menu.booking_button_text
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	booking_button_text: prismic.KeyTextField;
	
	/**
	 * Menu Links field in *Menu*
	 *
	 * - **Field Type**: Group
	 * - **Placeholder**: *None*
	 * - **API ID Path**: menu.menu_links[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
	 */
	menu_links: prismic.GroupField<Simplify<MenuDocumentDataMenuLinksItem>>;
}

/**
 * Menu document from Prismic
 *
 * - **API ID**: `menu`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MenuDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<MenuDocumentData>, "menu", Lang>;

type PageDocumentDataSlicesSlice = HeroSlice | ServiceGridSlice | ServicePageSlice | DoctorBlockSlice | PricelistSlice | TestimonialGridSlice | ContactBlockSlice | CtaBlockSlice | CeoBlockSlice | TestimonialBlockSlice | PartnerBlockSlice | PageTitleSlice | BlogGridSlice | BlogPageSlice | DoctorGridSlice

/**
 * Content for Page documents
 */
interface PageDocumentData {
	/**
	 * Slice Zone field in *Page*
	 *
	 * - **Field Type**: Slice Zone
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.slices[]
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/slices
	 */
	slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;

	/**
	 * SEO Title field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Enter page title for search engines
	 * - **API ID Path**: page.meta_title
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_title: prismic.KeyTextField;

	/**
	 * SEO Description field in *Page*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Enter page description for search engines
	 * - **API ID Path**: page.meta_description
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	meta_description: prismic.KeyTextField;

	/**
	 * Schema.org Image field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.schema_image
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	schema_image: prismic.ImageField<never>;

	/**
	 * Social Share Image (OpenGraph/Twitter) field in *Page*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: page.og_image
	 * - **Tab**: SEO
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	og_image: prismic.ImageField<never>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Content for Price Item documents
 */
interface PriceItemDocumentData {
	/**
	 * Category field in *Price Item*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Higiēna un profilakse
	 * - **API ID Path**: price_item.category
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	category: prismic.SelectField<"Higiēna un profilakse" | "Zobu implantācija un ķirurģija" | "Terapeitiskā zobārstniecība (plombēšana)" | "Estētiskā zobārstniecība un protezēšana" | "Ortodontija (kapes & breketes)", "filled">;
	
	/**
	 * Price Item Name field in *Price Item*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Profesionālā mutes dobuma higiēna
	 * - **API ID Path**: price_item.name
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * Price Value field in *Price Item*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 85 €
	 * - **API ID Path**: price_item.price
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	price: prismic.KeyTextField;
	
	/**
	 * Item Note / Subtitle field in *Price Item*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Ultrasonic scaler, air-flow...
	 * - **API ID Path**: price_item.note
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	note: prismic.KeyTextField;
	
	/**
	 * Display Order Index field in *Price Item*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: 1
	 * - **API ID Path**: price_item.order
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	order: prismic.NumberField;
}

/**
 * Price Item document from Prismic
 *
 * - **API ID**: `price_item`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PriceItemDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<PriceItemDocumentData>, "price_item", Lang>;

/**
 * Content for Service documents
 */
interface ServiceDocumentData {
	/**
	 * Title field in *Service*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Terapeitiskā zobārstniecība
	 * - **API ID Path**: service.title
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Short Description field in *Service*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Brief service summary...
	 * - **API ID Path**: service.description
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	description: prismic.KeyTextField;
	
	/**
	 * Detailed Info field in *Service*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Long descriptive paragraph of the service...
	 * - **API ID Path**: service.detailedInfo
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	detailedInfo: prismic.RichTextField;
	
	/**
	 * Price Range field in *Service*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: no 60 €
	 * - **API ID Path**: service.priceRange
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	priceRange: prismic.KeyTextField;
	
	/**
	 * Duration field in *Service*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 30 - 60 min
	 * - **API ID Path**: service.duration
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	duration: prismic.KeyTextField;
	
	/**
	 * Icon Name (Lucide) field in *Service*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: ShieldCheck, Sparkles, Droplet, Scissors, Activity
	 * - **API ID Path**: service.iconName
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	iconName: prismic.KeyTextField;
	
	/**
	 * Service Image field in *Service*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service.image
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Service document from Prismic
 *
 * - **API ID**: `service`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ServiceDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<ServiceDocumentData>, "service", Lang>;

/**
 * Content for Testimonial documents
 */
interface TestimonialDocumentData {
	/**
	 * Author Name field in *Testimonial*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Kristaps Zariņš
	 * - **API ID Path**: testimonial.author
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	author: prismic.KeyTextField;
	
	/**
	 * Initials field in *Testimonial*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: KZ
	 * - **API ID Path**: testimonial.initials
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	initials: prismic.KeyTextField;
	
	/**
	 * Background Color Class field in *Testimonial*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: bg-[#511B29] text-white
	 * - **API ID Path**: testimonial.bgColor
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	bgColor: prismic.KeyTextField;
	
	/**
	 * Treatment Received field in *Testimonial*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Zobu implantācija (Straumann)
	 * - **API ID Path**: testimonial.treatment
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	treatment: prismic.KeyTextField;
	
	/**
	 * Doctor Name field in *Testimonial*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Dr. Jānis Kalniņš
	 * - **API ID Path**: testimonial.doctor
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	doctor: prismic.KeyTextField;
	
	/**
	 * Rating (1-5) field in *Testimonial*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: 5
	 * - **API ID Path**: testimonial.rating
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	rating: prismic.NumberField;
	
	/**
	 * Date String field in *Testimonial*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 12.04.2026
	 * - **API ID Path**: testimonial.date
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	date: prismic.KeyTextField;
	
	/**
	 * Advantage Tag field in *Testimonial*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Premium kvalitāte
	 * - **API ID Path**: testimonial.advTag
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	advTag: prismic.KeyTextField;
	
	/**
	 * Short Quote Summary field in *Testimonial*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Painless Swiss implants...
	 * - **API ID Path**: testimonial.quote
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	quote: prismic.KeyTextField;
	
	/**
	 * Full Experience Story field in *Testimonial*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Full story detailed description...
	 * - **API ID Path**: testimonial.story
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	story: prismic.KeyTextField;
}

/**
 * Testimonial document from Prismic
 *
 * - **API ID**: `testimonial`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TestimonialDocument<Lang extends string = string> = prismic.PrismicDocumentWithUID<Simplify<TestimonialDocumentData>, "testimonial", Lang>;

/**
 * Content for Settings documents
 */
export interface SettingsDocumentData {
	/**
	 * Favicon field in *Settings*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.favicon
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	favicon: prismic.ImageField<never>;
	
	/**
	 * Main Color field in *Settings*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.main_color
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	main_color: prismic.ColorField;
	
	/**
	 * Header Color field in *Settings*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: settings.header_color
	 * - **Tab**: Main
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	header_color: prismic.ColorField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> = prismic.PrismicDocumentWithoutUID<Simplify<SettingsDocumentData>, "settings", Lang>;

export type AllDocumentTypes = BlogPostDocument | FooterDocument | HomepageDocument | MenuDocument | PageDocument | PriceItemDocument | ServiceDocument | TestimonialDocument | SettingsDocument;

/**
 * Primary content in *BlogGrid → Default → Primary*
 */
export interface BlogGridSliceDefaultPrimary {
	/**
	 * Hide Header field in *BlogGrid → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: blog_grid.default.primary.hideHeader
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	hideHeader: prismic.BooleanField;
}

/**
 * Primary content in *BlogGrid → Items*
 */
export interface BlogGridSliceDefaultItem {
	/**
	 * Badge Text / Category field in *BlogGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: PADOMS
	 * - **API ID Path**: blog_grid.items[].badge_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	badge_text: prismic.KeyTextField;
	
	/**
	 * Title field in *BlogGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Zobu balināšana: viss, kas jāzina
	 * - **API ID Path**: blog_grid.items[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Excerpt / Description field in *BlogGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Praktiski padomi drošai zobu balināšanai...
	 * - **API ID Path**: blog_grid.items[].excerpt
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	excerpt: prismic.KeyTextField;
	
	/**
	 * Link Text field in *BlogGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Lasīt rakstu
	 * - **API ID Path**: blog_grid.items[].link_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	link_text: prismic.KeyTextField;
	
	/**
	 * Link URL field in *BlogGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: /en/blogs/some-post
	 * - **API ID Path**: blog_grid.items[].link_url
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	link_url: prismic.KeyTextField;
	
	/**
	 * Custom Image (Optional Override) field in *BlogGrid → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_grid.items[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for BlogGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogGridSliceDefault = prismic.SharedSliceVariation<"default", Simplify<BlogGridSliceDefaultPrimary>, Simplify<BlogGridSliceDefaultItem>>;

/**
 * Slice variation for *BlogGrid*
 */
type BlogGridSliceVariation = BlogGridSliceDefault

/**
 * BlogGrid Shared Slice
 *
 * - **API ID**: `blog_grid`
 * - **Description**: Renders blog card previews from inline items or queries Prismic blog posts dynamically if empty.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogGridSlice = prismic.SharedSlice<"blog_grid", BlogGridSliceVariation>;

/**
 * Primary content in *BlogPage → Default → Primary*
 */
export interface BlogPageSliceDefaultPrimary {
	/**
	 * Hide Header field in *BlogPage → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: blog_page.default.primary.hideHeader
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	hideHeader: prismic.BooleanField;
}

/**
 * Primary content in *BlogPage → Items*
 */
export interface BlogPageSliceDefaultItem {
	/**
	 * Badge Text / Category field in *BlogPage → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: PADOMS
	 * - **API ID Path**: blog_page.items[].badge_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	badge_text: prismic.KeyTextField;
	
	/**
	 * Title field in *BlogPage → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Zobu balināšana: viss, kas jāzina
	 * - **API ID Path**: blog_page.items[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Excerpt / Description field in *BlogPage → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Praktiski padomi drošai zobu balināšanai...
	 * - **API ID Path**: blog_page.items[].excerpt
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	excerpt: prismic.KeyTextField;
	
	/**
	 * Link Text field in *BlogPage → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Lasīt rakstu
	 * - **API ID Path**: blog_page.items[].link_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	link_text: prismic.KeyTextField;
	
	/**
	 * Link URL (Content Relationship to single post) field in *BlogPage → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_page.items[].link_url
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	link_url: prismic.ContentRelationshipField<"blog_post">;
	
	/**
	 * Custom Image (Optional Override) field in *BlogPage → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: blog_page.items[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for BlogPage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogPageSliceDefault = prismic.SharedSliceVariation<"default", Simplify<BlogPageSliceDefaultPrimary>, Simplify<BlogPageSliceDefaultItem>>;

/**
 * Slice variation for *BlogPage*
 */
type BlogPageSliceVariation = BlogPageSliceDefault

/**
 * BlogPage Shared Slice
 *
 * - **API ID**: `blog_page`
 * - **Description**: Renders the full grid of blog posts on the blogs page from inline items or queries Prismic dynamically.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BlogPageSlice = prismic.SharedSlice<"blog_page", BlogPageSliceVariation>;

/**
 * Primary content in *CEOBlock → Default → Primary*
 */
export interface CeoBlockSliceDefaultPrimary {
	/**
	 * Leader Tag field in *CEOBlock → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Klīnikas vadītājs un vadošais speciālists
	 * - **API ID Path**: ceo_block.default.primary.leader_tag
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	leader_tag: prismic.KeyTextField;
	
	/**
	 * Name field in *CEOBlock → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Dr. Jānis Bērziņš
	 * - **API ID Path**: ceo_block.default.primary.name
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	name: prismic.KeyTextField;
	
	/**
	 * Biography field in *CEOBlock → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Mūsu klīnikas filozofija balstās uz...
	 * - **API ID Path**: ceo_block.default.primary.biography
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	biography: prismic.RichTextField;
	
	/**
	 * Image field in *CEOBlock → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ceo_block.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * Signature Image field in *CEOBlock → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: ceo_block.default.primary.signature_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	signature_image: prismic.ImageField<never>;
	
	/**
	 * Link Text field in *CEOBlock → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Uzzināt vairāk
	 * - **API ID Path**: ceo_block.default.primary.link_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	link_text: prismic.KeyTextField;
	
	/**
	 * Link URL field in *CEOBlock → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Select page or enter URL
	 * - **API ID Path**: ceo_block.default.primary.link_url
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link_url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for CEOBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CeoBlockSliceDefault = prismic.SharedSliceVariation<"default", Simplify<CeoBlockSliceDefaultPrimary>, never>;

/**
 * Slice variation for *CEOBlock*
 */
type CeoBlockSliceVariation = CeoBlockSliceDefault

/**
 * CEOBlock Shared Slice
 *
 * - **API ID**: `ceo_block`
 * - **Description**: Renders the CEO/Clinic Director card block with bio, photo, signature, and learn more link.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CeoBlockSlice = prismic.SharedSlice<"ceo_block", CeoBlockSliceVariation>;

/**
 * Primary content in *ContactBlock → Items*
 */
export interface ContactBlockSliceDefaultItem {
	/**
	 * Branch Badge / Type field in *ContactBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Centrālā filiāle
	 * - **API ID Path**: contact_block.items[].badge_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	badge_text: prismic.KeyTextField;
	
	/**
	 * Clinic Name field in *ContactBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Dentamix Rīga
	 * - **API ID Path**: contact_block.items[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Phone Number field in *ContactBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: +371 29 459 999
	 * - **API ID Path**: contact_block.items[].phone
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	phone: prismic.KeyTextField;
	
	/**
	 * Address field in *ContactBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Brīvības iela 100, Rīga
	 * - **API ID Path**: contact_block.items[].address
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	address: prismic.KeyTextField;
	
	/**
	 * Email Address field in *ContactBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: riga@dentamix.lv
	 * - **API ID Path**: contact_block.items[].email
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	email: prismic.KeyTextField;
	
	/**
	 * Working Hours Section Title field in *ContactBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Darba laiks
	 * - **API ID Path**: contact_block.items[].working_hours_label
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	working_hours_label: prismic.KeyTextField;
	
	/**
	 * Weekdays Text field in *ContactBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Darba dienās:
	 * - **API ID Path**: contact_block.items[].weekday_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	weekday_text: prismic.KeyTextField;
	
	/**
	 * Saturday Text field in *ContactBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Sestdien:
	 * - **API ID Path**: contact_block.items[].saturday_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	saturday_text: prismic.KeyTextField;
	
	/**
	 * Sunday Text field in *ContactBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Svētdien:
	 * - **API ID Path**: contact_block.items[].sunday_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	sunday_text: prismic.KeyTextField;
	
	/**
	 * Weekday Hours field in *ContactBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 09:00 - 19:00
	 * - **API ID Path**: contact_block.items[].weekday_hours
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	weekday_hours: prismic.KeyTextField;
	
	/**
	 * Saturday Hours field in *ContactBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 10:00 - 15:00
	 * - **API ID Path**: contact_block.items[].saturday_hours
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	saturday_hours: prismic.KeyTextField;
	
	/**
	 * Sunday Hours field in *ContactBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Slēgts
	 * - **API ID Path**: contact_block.items[].sunday_hours
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	sunday_hours: prismic.KeyTextField;
	
	/**
	 * Accessibility Info Text field in *ContactBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Klīnika ir pilnībā pieejama ratiņkrēslā
	 * - **API ID Path**: contact_block.items[].accessibility_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	accessibility_text: prismic.KeyTextField;
	
	/**
	 * Google Maps Embed URL field in *ContactBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: https://www.google.com/maps/embed?pb=...
	 * - **API ID Path**: contact_block.items[].gmaps_iframe_url
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	gmaps_iframe_url: prismic.KeyTextField;
	
	/**
	 * Google Maps Direct Link / Share URL field in *ContactBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: https://maps.app.goo.gl/DvLgodzdiR5t2KQK8
	 * - **API ID Path**: contact_block.items[].gmaps_direct_url
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	gmaps_direct_url: prismic.KeyTextField;
	
	/**
	 * Map Link Title field in *ContactBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Karte / Google Maps
	 * - **API ID Path**: contact_block.items[].map_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	map_title: prismic.KeyTextField;
	
	/**
	 * Waze Directions Link field in *ContactBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: https://waze.com/ul/hud1k9wgd7
	 * - **API ID Path**: contact_block.items[].waze_url
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	waze_url: prismic.KeyTextField;
	
	/**
	 * Waze Link Title field in *ContactBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Waze
	 * - **API ID Path**: contact_block.items[].waze_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	waze_title: prismic.KeyTextField;
}

/**
 * Default variation for ContactBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactBlockSliceDefault = prismic.SharedSliceVariation<"default", Record<string, never>, Simplify<ContactBlockSliceDefaultItem>>;

/**
 * Slice variation for *ContactBlock*
 */
type ContactBlockSliceVariation = ContactBlockSliceDefault

/**
 * ContactBlock Shared Slice
 *
 * - **API ID**: `contact_block`
 * - **Description**: Customizable contacts block showing repeatable clinic cards in a single-column list design.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactBlockSlice = prismic.SharedSlice<"contact_block", ContactBlockSliceVariation>;

/**
 * Primary content in *CTABlock → Default → Primary*
 */
export interface CtaBlockSliceDefaultPrimary {
	/**
	 * Badge text field in *CTABlock → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Share Your Experience
	 * - **API ID Path**: cta_block.default.primary.badge_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	badge_text: prismic.KeyTextField;
	
	/**
	 * Title field in *CTABlock → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Would you like to leave a review of your visit?
	 * - **API ID Path**: cta_block.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Description field in *CTABlock → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Every patient's opinion helps us grow...
	 * - **API ID Path**: cta_block.default.primary.description
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	description: prismic.RichTextField;
	
	/**
	 * Button text field in *CTABlock → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Book a Visit
	 * - **API ID Path**: cta_block.default.primary.button_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	button_text: prismic.KeyTextField;
	
	/**
	 * Button Link field in *CTABlock → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Select page or enter URL
	 * - **API ID Path**: cta_block.default.primary.button_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	button_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Background Color field in *CTABlock → Default → Primary*
	 *
	 * - **Field Type**: Color
	 * - **Placeholder**: *None*
	 * - **API ID Path**: cta_block.default.primary.background_color
	 * - **Documentation**: https://prismic.io/docs/fields/color
	 */
	background_color: prismic.ColorField;
}

/**
 * Default variation for CTABlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaBlockSliceDefault = prismic.SharedSliceVariation<"default", Simplify<CtaBlockSliceDefaultPrimary>, never>;

/**
 * Slice variation for *CTABlock*
 */
type CtaBlockSliceVariation = CtaBlockSliceDefault

/**
 * CTABlock Shared Slice
 *
 * - **API ID**: `cta_block`
 * - **Description**: CTA block with badge, title, description, and button link fields
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CtaBlockSlice = prismic.SharedSlice<"cta_block", CtaBlockSliceVariation>;

/**
 * Primary content in *DoctorBlock → Doctor Detail → Primary*
 */
export interface DoctorBlockSliceDefaultPrimary {
	/**
	 * Full Biography (Upper text with vertical line) field in *DoctorBlock → Doctor Detail → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Dr. Jānis Kalniņš ir augsti sertificēts...
	 * - **API ID Path**: doctor_block.default.primary.fullBio
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	fullBio: prismic.RichTextField;
	
	/**
	 * Detailed Biography (Under doctor text) field in *DoctorBlock → Doctor Detail → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Enter detailed text like in a blog post...
	 * - **API ID Path**: doctor_block.default.primary.detailedBio
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	detailedBio: prismic.RichTextField;
	
	/**
	 * Photo field in *DoctorBlock → Doctor Detail → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: doctor_block.default.primary.image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
	
	/**
	 * Workplace Section Title field in *DoctorBlock → Doctor Detail → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Darba vieta
	 * - **API ID Path**: doctor_block.default.primary.workplace_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	workplace_title: prismic.KeyTextField;
	
	/**
	 * CTA Badge Text field in *DoctorBlock → Doctor Detail → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Pieraksts atvērts
	 * - **API ID Path**: doctor_block.default.primary.cta_badge_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_badge_text: prismic.KeyTextField;
	
	/**
	 * CTA Title field in *DoctorBlock → Doctor Detail → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Pieteikties uz vizīti
	 * - **API ID Path**: doctor_block.default.primary.cta_title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_title: prismic.KeyTextField;
	
	/**
	 * CTA Description field in *DoctorBlock → Doctor Detail → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Piesakieties vizītei vai konsultācijai...
	 * - **API ID Path**: doctor_block.default.primary.cta_description
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_description: prismic.KeyTextField;
	
	/**
	 * CTA Button Text field in *DoctorBlock → Doctor Detail → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Pieteikties vizītei
	 * - **API ID Path**: doctor_block.default.primary.cta_button_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_button_text: prismic.KeyTextField;
	
	/**
	 * CTA URL Link field in *DoctorBlock → Doctor Detail → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: *None*
	 * - **API ID Path**: doctor_block.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Open CTA link in new tab field in *DoctorBlock → Doctor Detail → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: doctor_block.default.primary.cta_link_blank
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	cta_link_blank: prismic.BooleanField;
}

/**
 * Primary content in *DoctorBlock → Items*
 */
export interface DoctorBlockSliceDefaultItem {
	/**
	 * Item Type field in *DoctorBlock → Items*
	 *
	 * - **Field Type**: Select
	 * - **Placeholder**: *None*
	 * - **Default Value**: Specialization
	 * - **API ID Path**: doctor_block.items[].item_type
	 * - **Documentation**: https://prismic.io/docs/fields/select
	 */
	item_type: prismic.SelectField<"Specialization" | "Education" | "Qualification" | "Workplace" | "Language", "filled">;
	
	/**
	 * Text Content field in *DoctorBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: e.g., Dental implants or Latvian
	 * - **API ID Path**: doctor_block.items[].text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	text: prismic.KeyTextField;
}

/**
 * Doctor Detail variation for DoctorBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Renders a detailed profile page for a single doctor
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DoctorBlockSliceDefault = prismic.SharedSliceVariation<"default", Simplify<DoctorBlockSliceDefaultPrimary>, Simplify<DoctorBlockSliceDefaultItem>>;

/**
 * Slice variation for *DoctorBlock*
 */
type DoctorBlockSliceVariation = DoctorBlockSliceDefault

/**
 * DoctorBlock Shared Slice
 *
 * - **API ID**: `doctor_block`
 * - **Description**: Featured doctors block with title, subtitle, and repeatable selected doctors.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DoctorBlockSlice = prismic.SharedSlice<"doctor_block", DoctorBlockSliceVariation>;

/**
 * Primary content in *DoctorGrid → Default → Primary*
 */
export interface DoctorGridSliceDefaultPrimary {
	/**
	 * Hide Header (use when PageTitle slice is above) field in *DoctorGrid → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: doctor_grid.default.primary.hideHeader
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	hideHeader: prismic.BooleanField;
}

/**
 * Primary content in *DoctorGrid → Items*
 */
export interface DoctorGridSliceDefaultItem {
	/**
	 * Badge / Role field in *DoctorGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: SPECIĀLISTE
	 * - **API ID Path**: doctor_grid.items[].badge_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	badge_text: prismic.KeyTextField;
	
	/**
	 * Doctor Name field in *DoctorGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Dr. Anna Bērziņa
	 * - **API ID Path**: doctor_grid.items[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Short Bio / Excerpt field in *DoctorGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Pieredzējusi estētiskās zobārstniecības speciāliste...
	 * - **API ID Path**: doctor_grid.items[].excerpt
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	excerpt: prismic.KeyTextField;
	
	/**
	 * Profile Link Text field in *DoctorGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Skatīt profilu
	 * - **API ID Path**: doctor_grid.items[].link_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	link_text: prismic.KeyTextField;
	
	/**
	 * Profile Link URL field in *DoctorGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: /zobarsti/dr-anna-berzina
	 * - **API ID Path**: doctor_grid.items[].link_url
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	link_url: prismic.KeyTextField;
	
	/**
	 * Book Button Text field in *DoctorGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Pieteikties
	 * - **API ID Path**: doctor_grid.items[].book_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	book_text: prismic.KeyTextField;
	
	/**
	 * Book Button URL field in *DoctorGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: /kontakti
	 * - **API ID Path**: doctor_grid.items[].book_url
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	book_url: prismic.KeyTextField;
	
	/**
	 * Open Booking URL in New Tab field in *DoctorGrid → Items*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: false
	 * - **API ID Path**: doctor_grid.items[].book_url_blank
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	book_url_blank: prismic.BooleanField;
	
	/**
	 * Show Book Button field in *DoctorGrid → Items*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: doctor_grid.items[].show_book_button
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	show_book_button: prismic.BooleanField;
	
	/**
	 * Doctor Photo field in *DoctorGrid → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: doctor_grid.items[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for DoctorGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DoctorGridSliceDefault = prismic.SharedSliceVariation<"default", Simplify<DoctorGridSliceDefaultPrimary>, Simplify<DoctorGridSliceDefaultItem>>;

/**
 * Slice variation for *DoctorGrid*
 */
type DoctorGridSliceVariation = DoctorGridSliceDefault

/**
 * DoctorGrid Shared Slice
 *
 * - **API ID**: `doctor_grid`
 * - **Description**: Inline doctor cards grid for the /doctors page. Add each doctor as an item with image, name, role, excerpt, profile link and booking link.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type DoctorGridSlice = prismic.SharedSlice<"doctor_grid", DoctorGridSliceVariation>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
	/**
	 * Title field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Izcila zobārstniecība Jūsu labsajūtai
	 * - **API ID Path**: hero.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Subtitle field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Modernas tehnoloģijas un individuāla pieeja...
	 * - **API ID Path**: hero.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	subtitle: prismic.RichTextField;
	
	/**
	 * Premium tag text field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Premium Care
	 * - **API ID Path**: hero.default.primary.premium_tag
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	premium_tag: prismic.KeyTextField;
	
	/**
	 * Primary CTA text field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Pierakstīties vizītei
	 * - **API ID Path**: hero.default.primary.cta_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	cta_text: prismic.KeyTextField;
	
	/**
	 * Primary CTA Link field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Select page or enter URL
	 * - **API ID Path**: hero.default.primary.cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Secondary CTA text field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Mūsu pakalpojumi
	 * - **API ID Path**: hero.default.primary.secondary_cta_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	secondary_cta_text: prismic.KeyTextField;
	
	/**
	 * Secondary CTA Link field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Select page or enter URL
	 * - **API ID Path**: hero.default.primary.secondary_cta_link
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	secondary_cta_link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
	
	/**
	 * Background Image field in *Hero → Default → Primary*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: hero.default.primary.background_image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	background_image: prismic.ImageField<never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Hero default section
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<"default", Simplify<HeroSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation = HeroSliceDefault

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero section with title, subtitle, and CTA buttons
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *PageTitle → Default → Primary*
 */
export interface PageTitleSliceDefaultPrimary {
	/**
	 * Badge Text field in *PageTitle → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: DENTAMIC PRIEKŠROCĪBAS
	 * - **API ID Path**: page_title.default.primary.badge_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	badge_text: prismic.KeyTextField;
	
	/**
	 * Title field in *PageTitle → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Pacientu atsauksmes
	 * - **API ID Path**: page_title.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Subtitle field in *PageTitle → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Mūsu pacientu patiesas atsauksmes...
	 * - **API ID Path**: page_title.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	subtitle: prismic.KeyTextField;
}

/**
 * Default variation for PageTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PageTitleSliceDefault = prismic.SharedSliceVariation<"default", Simplify<PageTitleSliceDefaultPrimary>, never>;

/**
 * Slice variation for *PageTitle*
 */
type PageTitleSliceVariation = PageTitleSliceDefault

/**
 * PageTitle Shared Slice
 *
 * - **API ID**: `page_title`
 * - **Description**: Renders a standard centered page title block with a badge, heading, and subheading.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PageTitleSlice = prismic.SharedSlice<"page_title", PageTitleSliceVariation>;

/**
 * Primary content in *PartnerBlock → Default → Primary*
 */
export interface PartnerBlockSliceDefaultPrimary {
	/**
	 * Badge Text field in *PartnerBlock → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Pacientu drošība un tehnoloģijas
	 * - **API ID Path**: partner_block.default.primary.badge_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	badge_text: prismic.KeyTextField;
	
	/**
	 * Title field in *PartnerBlock → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Mūsu partneri
	 * - **API ID Path**: partner_block.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Subtitle field in *PartnerBlock → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Sadarbojamies ar pasaulē vadošajiem...
	 * - **API ID Path**: partner_block.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	subtitle: prismic.KeyTextField;
}

/**
 * Primary content in *PartnerBlock → Items*
 */
export interface PartnerBlockSliceDefaultItem {
	/**
	 * Partner Logo field in *PartnerBlock → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: partner_block.items[].logo
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	logo: prismic.ImageField<never>;
}

/**
 * Default variation for PartnerBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PartnerBlockSliceDefault = prismic.SharedSliceVariation<"default", Simplify<PartnerBlockSliceDefaultPrimary>, Simplify<PartnerBlockSliceDefaultItem>>;

/**
 * Slice variation for *PartnerBlock*
 */
type PartnerBlockSliceVariation = PartnerBlockSliceDefault

/**
 * PartnerBlock Shared Slice
 *
 * - **API ID**: `partner_block`
 * - **Description**: Renders a grid of partner logos with custom titles and countries.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PartnerBlockSlice = prismic.SharedSlice<"partner_block", PartnerBlockSliceVariation>;

/**
 * Primary content in *Pricelist → Default → Primary*
 */
export interface PricelistSliceDefaultPrimary {
	/**
	 * Title field in *Pricelist → Default → Primary*
	 *
	 * - **Field Type**: Rich Text
	 * - **Placeholder**: Caurspīdīgas cenas un kvalitāte
	 * - **API ID Path**: pricelist.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/rich-text
	 */
	title: prismic.RichTextField;
	
	/**
	 * Subtitle field in *Pricelist → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Skaidrs un saprotams cenrādis...
	 * - **API ID Path**: pricelist.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	subtitle: prismic.KeyTextField;
}

/**
 * Default variation for Pricelist Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PricelistSliceDefault = prismic.SharedSliceVariation<"default", Simplify<PricelistSliceDefaultPrimary>, never>;

/**
 * Slice variation for *Pricelist*
 */
type PricelistSliceVariation = PricelistSliceDefault

/**
 * Pricelist Shared Slice
 *
 * - **API ID**: `pricelist`
 * - **Description**: Renders the price categories and price lists tables.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type PricelistSlice = prismic.SharedSlice<"pricelist", PricelistSliceVariation>;

/**
 * Primary content in *ServiceGrid → Default → Primary*
 */
export interface ServiceGridSliceDefaultPrimary {
	/**
	 * Hide Header (use when PageTitle slice is above) field in *ServiceGrid → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: service_grid.default.primary.hideHeader
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	hideHeader: prismic.BooleanField;
}

/**
 * Primary content in *ServiceGrid → Items*
 */
export interface ServiceGridSliceDefaultItem {
	/**
	 * Badge Text / Category field in *ServiceGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: PAKALPOJUMS
	 * - **API ID Path**: service_grid.items[].badge_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	badge_text: prismic.KeyTextField;
	
	/**
	 * Service Name field in *ServiceGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Zobu higiēna
	 * - **API ID Path**: service_grid.items[].title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Excerpt / Description field in *ServiceGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Mutes dobuma veselības uzturēšanai...
	 * - **API ID Path**: service_grid.items[].excerpt
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	excerpt: prismic.KeyTextField;
	
	/**
	 * Link Text field in *ServiceGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Lasīt vairāk
	 * - **API ID Path**: service_grid.items[].link_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	link_text: prismic.KeyTextField;
	
	/**
	 * Link URL field in *ServiceGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: /pakalpojumi/higiene
	 * - **API ID Path**: service_grid.items[].link_url
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	link_url: prismic.KeyTextField;
	
	/**
	 * Service Image field in *ServiceGrid → Items*
	 *
	 * - **Field Type**: Image
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_grid.items[].image
	 * - **Documentation**: https://prismic.io/docs/fields/image
	 */
	image: prismic.ImageField<never>;
}

/**
 * Default variation for ServiceGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceGridSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ServiceGridSliceDefaultPrimary>, Simplify<ServiceGridSliceDefaultItem>>;

/**
 * Slice variation for *ServiceGrid*
 */
type ServiceGridSliceVariation = ServiceGridSliceDefault

/**
 * ServiceGrid Shared Slice
 *
 * - **API ID**: `service_grid`
 * - **Description**: Services grid cards with + add item in repeatable zone.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServiceGridSlice = prismic.SharedSlice<"service_grid", ServiceGridSliceVariation>;

/**
 * Primary content in *ServicePage → Default → Primary*
 */
export interface ServicePageSliceDefaultPrimary {
	/**
	 * Hide Header field in *ServicePage → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: service_page.default.primary.hideHeader
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	hideHeader: prismic.BooleanField;
}

/**
 * Primary content in *ServicePage → Items*
 */
export interface ServicePageSliceDefaultItem {
	/**
	 * Service Document field in *ServicePage → Items*
	 *
	 * - **Field Type**: Content Relationship
	 * - **Placeholder**: *None*
	 * - **API ID Path**: service_page.items[].service
	 * - **Documentation**: https://prismic.io/docs/fields/content-relationship
	 */
	service: prismic.ContentRelationshipField<"service">;
}

/**
 * Default variation for ServicePage Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicePageSliceDefault = prismic.SharedSliceVariation<"default", Simplify<ServicePageSliceDefaultPrimary>, Simplify<ServicePageSliceDefaultItem>>;

/**
 * Slice variation for *ServicePage*
 */
type ServicePageSliceVariation = ServicePageSliceDefault

/**
 * ServicePage Shared Slice
 *
 * - **API ID**: `service_page`
 * - **Description**: Renders the full grid of dental services on the services page.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ServicePageSlice = prismic.SharedSlice<"service_page", ServicePageSliceVariation>;

/**
 * Primary content in *TestimonialBlock → Default → Primary*
 */
export interface TestimonialBlockSliceDefaultPrimary {
	/**
	 * Hide Header field in *TestimonialBlock → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: testimonial_block.default.primary.hideHeader
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	hideHeader: prismic.BooleanField;
	
	/**
	 * Badge Text field in *TestimonialBlock → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Pacientu atsauksmes
	 * - **API ID Path**: testimonial_block.default.primary.badge_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	badge_text: prismic.KeyTextField;
	
	/**
	 * Title field in *TestimonialBlock → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Atsauksmes
	 * - **API ID Path**: testimonial_block.default.primary.title
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	title: prismic.KeyTextField;
	
	/**
	 * Subtitle field in *TestimonialBlock → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Mūsu pacienti novērtē...
	 * - **API ID Path**: testimonial_block.default.primary.subtitle
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	subtitle: prismic.KeyTextField;
	
	/**
	 * Section Link Text field in *TestimonialBlock → Default → Primary*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Skatīt visus pacientu stāstus
	 * - **API ID Path**: testimonial_block.default.primary.link_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	link_text: prismic.KeyTextField;
	
	/**
	 * Section Link URL field in *TestimonialBlock → Default → Primary*
	 *
	 * - **Field Type**: Link
	 * - **Placeholder**: Select page or enter URL
	 * - **API ID Path**: testimonial_block.default.primary.link_url
	 * - **Documentation**: https://prismic.io/docs/fields/link
	 */
	link_url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Primary content in *TestimonialBlock → Items*
 */
export interface TestimonialBlockSliceDefaultItem {
	/**
	 * Testimonial Tagline / Treatment field in *TestimonialBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Zobu implantācija
	 * - **API ID Path**: testimonial_block.items[].tagline
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	tagline: prismic.KeyTextField;
	
	/**
	 * Author field in *TestimonialBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Anna Bērziņa
	 * - **API ID Path**: testimonial_block.items[].author
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	author: prismic.KeyTextField;
	
	/**
	 * Testimonial Text / Story field in *TestimonialBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Lieliska attieksme un nesāpīga procedūra...
	 * - **API ID Path**: testimonial_block.items[].testimonial_text
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	testimonial_text: prismic.KeyTextField;
	
	/**
	 * Date field in *TestimonialBlock → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 12. Maijs, 2026
	 * - **API ID Path**: testimonial_block.items[].date
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	date: prismic.KeyTextField;
	
	/**
	 * Rating (1-5) field in *TestimonialBlock → Items*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: 5
	 * - **API ID Path**: testimonial_block.items[].rating
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	rating: prismic.NumberField;
}

/**
 * Default variation for TestimonialBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialBlockSliceDefault = prismic.SharedSliceVariation<"default", Simplify<TestimonialBlockSliceDefaultPrimary>, Simplify<TestimonialBlockSliceDefaultItem>>;

/**
 * Slice variation for *TestimonialBlock*
 */
type TestimonialBlockSliceVariation = TestimonialBlockSliceDefault

/**
 * TestimonialBlock Shared Slice
 *
 * - **API ID**: `testimonial_block`
 * - **Description**: Renders testimonial cards in a 3-column bento-like grid with editable fields and customizable CTA links.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialBlockSlice = prismic.SharedSlice<"testimonial_block", TestimonialBlockSliceVariation>;

/**
 * Primary content in *TestimonialGrid → Default → Primary*
 */
export interface TestimonialGridSliceDefaultPrimary {
	/**
	 * Hide Header field in *TestimonialGrid → Default → Primary*
	 *
	 * - **Field Type**: Boolean
	 * - **Placeholder**: *None*
	 * - **Default Value**: true
	 * - **API ID Path**: testimonial_grid.default.primary.hideHeader
	 * - **Documentation**: https://prismic.io/docs/fields/boolean
	 */
	hideHeader: prismic.BooleanField;
}

/**
 * Primary content in *TestimonialGrid → Items*
 */
export interface TestimonialGridSliceDefaultItem {
	/**
	 * Author Name field in *TestimonialGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Juris K.
	 * - **API ID Path**: testimonial_grid.items[].author
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	author: prismic.KeyTextField;
	
	/**
	 * Treatment Type field in *TestimonialGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: Zobu implantācija
	 * - **API ID Path**: testimonial_grid.items[].treatment
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	treatment: prismic.KeyTextField;
	
	/**
	 * Rating (1-5) field in *TestimonialGrid → Items*
	 *
	 * - **Field Type**: Number
	 * - **Placeholder**: 5
	 * - **API ID Path**: testimonial_grid.items[].rating
	 * - **Documentation**: https://prismic.io/docs/fields/number
	 */
	rating: prismic.NumberField;
	
	/**
	 * Date field in *TestimonialGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: 10. Maijs, 2026
	 * - **API ID Path**: testimonial_grid.items[].date
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	date: prismic.KeyTextField;
	
	/**
	 * Detailed Story field in *TestimonialGrid → Items*
	 *
	 * - **Field Type**: Text
	 * - **Placeholder**: The implant surgery was completely painless...
	 * - **API ID Path**: testimonial_grid.items[].story
	 * - **Documentation**: https://prismic.io/docs/fields/text
	 */
	story: prismic.KeyTextField;
}

/**
 * Default variation for TestimonialGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default variation
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialGridSliceDefault = prismic.SharedSliceVariation<"default", Simplify<TestimonialGridSliceDefaultPrimary>, Simplify<TestimonialGridSliceDefaultItem>>;

/**
 * Slice variation for *TestimonialGrid*
 */
type TestimonialGridSliceVariation = TestimonialGridSliceDefault

/**
 * TestimonialGrid Shared Slice
 *
 * - **API ID**: `testimonial_grid`
 * - **Description**: Renders testimonial cards from inline items or queries Prismic testimonial documents if empty.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type TestimonialGridSlice = prismic.SharedSlice<"testimonial_grid", TestimonialGridSliceVariation>;

declare module "@prismicio/client" {
	interface CreateClient {
		(repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
	}
	
	interface CreateWriteClient {
		(repositoryNameOrEndpoint: string, options: prismic.WriteClientConfig): prismic.WriteClient<AllDocumentTypes>;
	}
	
	interface CreateMigration {
		(): prismic.Migration<AllDocumentTypes>;
	}
	
	namespace Content {
		export type {
			BlogPostDocument,
			BlogPostDocumentData,
			FooterDocument,
			FooterDocumentData,
			FooterDocumentDataClinicsItem,
			HomepageDocument,
			HomepageDocumentData,
			HomepageDocumentDataSlicesSlice,
			MenuDocument,
			MenuDocumentData,
			MenuDocumentDataMenuLinksItem,
			PageDocument,
			PageDocumentData,
			PageDocumentDataSlicesSlice,
			PriceItemDocument,
			PriceItemDocumentData,
			ServiceDocument,
			ServiceDocumentData,
			TestimonialDocument,
			TestimonialDocumentData,
			SettingsDocument,
			SettingsDocumentData,
			AllDocumentTypes,
			BlogGridSlice,
			BlogGridSliceDefaultPrimary,
			BlogGridSliceDefaultItem,
			BlogGridSliceVariation,
			BlogGridSliceDefault,
			BlogPageSlice,
			BlogPageSliceDefaultPrimary,
			BlogPageSliceDefaultItem,
			BlogPageSliceVariation,
			BlogPageSliceDefault,
			CeoBlockSlice,
			CeoBlockSliceDefaultPrimary,
			CeoBlockSliceVariation,
			CeoBlockSliceDefault,
			ContactBlockSlice,
			ContactBlockSliceDefaultItem,
			ContactBlockSliceVariation,
			ContactBlockSliceDefault,
			CtaBlockSlice,
			CtaBlockSliceDefaultPrimary,
			CtaBlockSliceVariation,
			CtaBlockSliceDefault,
			DoctorBlockSlice,
			DoctorBlockSliceDefaultPrimary,
			DoctorBlockSliceDefaultItem,
			DoctorBlockSliceVariation,
			DoctorBlockSliceDefault,
			DoctorGridSlice,
			DoctorGridSliceDefaultPrimary,
			DoctorGridSliceDefaultItem,
			DoctorGridSliceVariation,
			DoctorGridSliceDefault,
			HeroSlice,
			HeroSliceDefaultPrimary,
			HeroSliceVariation,
			HeroSliceDefault,
			PageTitleSlice,
			PageTitleSliceDefaultPrimary,
			PageTitleSliceVariation,
			PageTitleSliceDefault,
			PartnerBlockSlice,
			PartnerBlockSliceDefaultPrimary,
			PartnerBlockSliceDefaultItem,
			PartnerBlockSliceVariation,
			PartnerBlockSliceDefault,
			PricelistSlice,
			PricelistSliceDefaultPrimary,
			PricelistSliceVariation,
			PricelistSliceDefault,
			ServiceGridSlice,
			ServiceGridSliceDefaultPrimary,
			ServiceGridSliceDefaultItem,
			ServiceGridSliceVariation,
			ServiceGridSliceDefault,
			ServicePageSlice,
			ServicePageSliceDefaultPrimary,
			ServicePageSliceDefaultItem,
			ServicePageSliceVariation,
			ServicePageSliceDefault,
			TestimonialBlockSlice,
			TestimonialBlockSliceDefaultPrimary,
			TestimonialBlockSliceDefaultItem,
			TestimonialBlockSliceVariation,
			TestimonialBlockSliceDefault,
			TestimonialGridSlice,
			TestimonialGridSliceDefaultPrimary,
			TestimonialGridSliceDefaultItem,
			TestimonialGridSliceVariation,
			TestimonialGridSliceDefault
		}
	}
}