// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  service_grid: dynamic(() => import("./ServiceGrid")),
  service_page: dynamic(() => import("./ServicePage")),
  widget_block: dynamic(() => import("./WidgetBlock")),
  pricelist: dynamic(() => import("./Pricelist")),
  testimonial_grid: dynamic(() => import("./TestimonialGrid")),
  contact_block: dynamic(() => import("./ContactBlock")),
  cta_block: dynamic(() => import("./CTABlock")),
  ceo_block: dynamic(() => import("./CEOBlock")),
  testimonial_block: dynamic(() => import("./TestimonialBlock")),
  partner_block: dynamic(() => import("./PartnerBlock")),
  page_title: dynamic(() => import("./PageTitle")),
  page_block: dynamic(() => import("./PageBlock")),
  blog_grid: dynamic(() => import("./BlogGrid")),
  blog_page: dynamic(() => import("./BlogPage")),
  doctor_grid: dynamic(() => import("./DoctorGrid")),
  faq_block: dynamic(() => import("./FAQBlock")),
  photo_block: dynamic(() => import("./PhotoBlock")),
};
