// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  service_grid: dynamic(() => import("./ServiceGrid")),
  service_page: dynamic(() => import("./ServicePage")),
  doctor_block: dynamic(() => import("./DoctorBlock")),
  doctor_page: dynamic(() => import("./DoctorPage")),
  pricelist: dynamic(() => import("./Pricelist")),
  testimonial_card: dynamic(() => import("./TestimonialCard")),
  contact_block: dynamic(() => import("./ContactBlock")),
  cta_block: dynamic(() => import("./CTABlock")),
  ceo_block: dynamic(() => import("./CEOBlock")),
  testimonial_block: dynamic(() => import("./TestimonialBlock")),
  partner_block: dynamic(() => import("./PartnerBlock")),
  page_title: dynamic(() => import("./PageTitle")),
  blog_block: dynamic(() => import("./BlogBlock")),
  blog_page: dynamic(() => import("./BlogPage")),
  doctor_grid: dynamic(() => import("./DoctorGrid")),
};
