// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero: dynamic(() => import("./Hero")),
  services_list: dynamic(() => import("./ServicesList")),
  doctors_list: dynamic(() => import("./DoctorsList")),
  pricelist: dynamic(() => import("./Pricelist")),
  testimonials_list: dynamic(() => import("./TestimonialsList")),
  contact_form: dynamic(() => import("./ContactForm")),
  cta_block: dynamic(() => import("./CTABlock")),
  ceo_block: dynamic(() => import("./CEOBlock")),
  testimonial_block: dynamic(() => import("./TestimonialBlock")),
};
