'use client';

import React from 'react';
import { ArrowLeft } from 'lucide-react';
import { motion } from 'motion/react';
import { useParams } from 'next/navigation';
import Link from 'next/link';

export default function CookiesClient() {
  const params = useParams();
  const langList = params?.lang;
  const isEn = langList === 'en' || (Array.isArray(langList) && langList[0] === 'en');
  const langPrefix = isEn ? '/en' : '';

  const fadeUpVariants = {
    hidden: { opacity: 0, y: 12 },
    visible: {
      opacity: 1,
      y: 0,
      transition: { type: 'tween', ease: 'easeOut', duration: 0.55 }
    }
  } as const;

  const staggerContainer = {
    hidden: {},
    visible: {
      transition: { staggerChildren: 0.12, delayChildren: 0.05 }
    }
  } as const;

  return (
    <motion.div
      initial="hidden"
      animate="visible"
      variants={staggerContainer}
      className="py-16 md:py-24 max-w-7xl mx-auto px-6"
    >
      {/* Header Metadata block */}
      <motion.div variants={fadeUpVariants} className="text-center w-full mb-12 animate-fade-in">
        <span className="text-[10px] font-extrabold uppercase tracking-widest text-[#de7c8a] mb-3 block text-center">
          {isEn ? 'Cookie Policy' : 'Sīkdatņu politika'}
        </span>
        <h2 className="text-3xl sm:text-4xl font-serif font-bold text-[#511B29] tracking-tight leading-tight mb-6 text-center w-full">
          {isEn
            ? 'Cookie Policy'
            : 'Sīkdatņu politika'}
        </h2>
      </motion.div>

      {/* Article Content */}
      <motion.div variants={fadeUpVariants} className="space-y-6">
        <div className="text-base leading-relaxed text-slate-800 space-y-6 font-normal">
          {isEn ? (
            <>
              <h3 className="text-lg font-serif font-bold text-[#511B29] pt-4">1. General Information</h3>
              <p>
                The website dentamix.lv (hereinafter – the Website) is operated by SIA "Dentamix", registration number 40103225875, legal address Brīvības iela 97-5, Rīga, LV-1001 (hereinafter – the Dental Clinic). Contact information regarding personal data processing: phone 29419999, info@dentamix.lv. To ensure a better user experience, the Website uses cookies. By using the Website and clicking the "accept" button in the pop-up window, you consent to the use of cookies. You may withdraw your consent at any time by deleting the cookies stored in your browser. The Dental Clinic encourages you to carefully read this Cookie Policy and periodically review it to obtain up-to-date information about the Dental Clinic's personal data processing activities. Additional information about the Dental Clinic's processing of personal data can be found in the Dental Clinic's Privacy Policy.
              </p>

              <h3 className="text-lg font-serif font-bold text-[#511B29] pt-4">2. What Are Cookies and How Are They Used</h3>
              <p>
                Cookies are small text files that are sent to your computer's memory when you visit a website. On each subsequent visit, cookies are sent back to the originating website or to another website that recognises this cookie. Cookies act as a specific website's memory, allowing the page to remember your computer on subsequent visits, including remembering your settings or improving user convenience. The main purpose of cookies is to recognise the device with which you access the website, thus providing website content specifically tailored to each visitor (for example, the language you have chosen, text size, etc.), as well as providing statistics to the website owner that allows for further improvement of the website's functionality. The website also contains third-party cookies that collect information about you across different devices and marketing channels.
              </p>
              <p>
                This website uses the program "Google Analytics" by "Google Inc", which uses cookies stored on your computer and allows analysis of how you use the relevant website. The information generated by these cookies about how you use this website is sent to a "Google" server in the USA and stored there. Your IP address, using IP anonymisation, is shortened within the territory of the European Union or the European Economic Area and only in exceptional cases may be transferred for processing to Google servers located in the USA. "Google" uses this information to evaluate how you use the relevant website, to prepare reports for website operators on activities on the relevant websites and to provide other services related to website and internet usage. "Google" shall under no circumstances associate the IP address received here with any other information in "Google's" possession. "Google" may provide this information to third parties if required by law or if third parties process this data on behalf of "Google". For additional information about cookies, please visit allaboutcookies.org.
              </p>

              <h3 className="text-lg font-serif font-bold text-[#511B29] pt-4">3. Refusing the Use of Cookies</h3>
              <p>
                When visiting the website for the first time, a pop-up window will offer you the option to consent (button "I agree to cookies") to the use of cookies, as well as give you the opportunity to customise your consent and choose which types of cookies you wish to disable on your device. All cookies that are not considered essential may only be used with your prior consent. The Dental Clinic draws attention to the fact that essential cookies are a condition for using the website, thus no consent is required for their use. You have the right to refuse the creation, accumulation and processing of such statistical data at any time by manually disabling the use of the cookie processing mechanism in your browser. You can change cookie settings or delete them in your internet browser settings.
              </p>

              <h3 className="text-lg font-serif font-bold text-[#511B29] pt-4">4. Updates to the Cookie Policy</h3>
              <p>
                Technical website updates may occur from time to time, which may result in corrections or additions to the Cookie Policy. The Dental Clinic regularly updates the current version of the Cookie Policy on the website.
              </p>
            </>
          ) : (
            <>
              <h3 className="text-lg font-serif font-bold text-[#511B29] pt-4">1. Vispārēja informācija</h3>
              <p>
                Tīmekļvietni dentamix.lv ( turpmāk – tīmekļvietne ) uztur SIA "Dentamix", reģistrācijas numurs 40103225875, juridiskā adrese Brīvības iela 97-5, Rīga, LV-1001 (turpmāk – Zobārstniecība). Kontaktinformācija ar personas datu apstrādi saistītos jautājumos: tālrunis 29419999, info@dentamix.lv. Lai nodrošinātu labāku lietošanas pieredzi, tīmekļvietne izmanto sīkdatnes (angļu valodā – cookies). Lietojot tīmekļvietni un uzspiežot uznirstošajā logā pogu "apstiprināt", jūs piekrītat sīkdatņu izmantošanai. Savu piekrišanu jūs varat jebkurā laikā atsaukt, nodzēšot savā pārlūkprogrammā saglabātās sīkdatnes. Zobārstniecība aicina rūpīgi iepazīties ar šo Sīkdatņu politiku, kā arī periodiski to pārskatīt, lai iegūtu aktuālo informāciju par Zobārstniecības veiktajiem personas datu apstrādes procesiem. Papildus informāciju par Zobārstniecības veikto personas datu apstrādi var atrast Zobārstniecības Privātuma politikā.
              </p>

              <h3 className="text-lg font-serif font-bold text-[#511B29] pt-4">2. Kas ir sīkdatnes un kā tās izmanto</h3>
              <p>
                Sīkdatnes ir nelielas teksta datnes, kas tiek nosūtītas uz jūsu datora atmiņu tīmekļa vietnes apmeklējuma laikā. Katrā turpmākajā apmeklējuma reizē sīkdatnes tiek nosūtītas atpakaļ uz izcelsmes vietni vai uz citu vietni, kas atpazīst šo sīkdatni. Sīkdatnes darbojas kā konkrētas tīmekļa vietnes atmiņa, ļaujot šai lapai atcerēties jūsu datoru nākamajās apmeklējuma reizēs, tai skaitā sīkdatnes var atcerēties jūsu iestādījumus vai uzlabot lietotāja ērtības. Sīkdatnes galvenais mērķis ir atpazīt ierīci, ar kuru jūs piekļūstat tīmekļvietnei, tādējādi nodrošinot tīmekļvietnes saturu, kas īpaši pielāgots katram tīmekļvietnes apmeklētājam (piemēram, valodu, kuru esat izvēlējies, teksta lielumu u.tml.), kā arī sniegt statistiku tīmekļvietnes īpašniekam, kas ļauj papildus uzlabot tīmekļvietnes darbību. Tīmekļvietnē izvietotas arī trešo pušu sīkdatnes, kas apkopo informāciju par jums dažādās ierīcēs un mārketinga kanālos.
              </p>
              <p>
                Šajā tīmekļvietnē tiek izmantota uzņēmuma "Google Inc" programma "Google Analytics", kura izmanto sīkdatnes, kas tiek glabātas jūsu datorā un ļauj analizēt to, kā izmantojat attiecīgo interneta lapu. Šo sīkdatņu radītā informācija par to, kā izmantojat šo interneta lapu, tiek nosūtīta uz "Google" serveri ASV un tur saglabāta. Jūsu IP adrese, pielietojot IP - anonimizāciju, tiek saīsināta Eiropas Savienības vai Eiropas ekonomiskās zonas teritorijā un tikai izņēmuma gadījumos var tikt nodota apstrādei ASV atrodošos Google serveros. "Google" izmanto šo informāciju, lai izvērtētu to, kā izmantojat attiecīgo interneta lapu, lai interneta lapu uzturētājiem sagatavotu ziņojumus par aktivitātēm attiecīgajās interneta lapās un sniegtu citus ar interneta lapu un interneta izmantošanu saistītus pakalpojumus. "Google" nekādā gadījumā nesaista šeit saņemto IP adresi ar jebkuru citu informāciju, kura ir "Google" rīcībā. "Google" nepieciešamības gadījumā šo informāciju var sniegt trešajām personām, ja tas ir likumos noteikts vai ja trešās personas uzņēmuma "Google" uzdevumā veic šo datu apstrādi. Lai saņemtu citu papildu informāciju par sīkdatnēm, aicinām apmeklēt allaboutcookies.org.
              </p>

              <h3 className="text-lg font-serif font-bold text-[#511B29] pt-4">3. Atteikšanās no sīkdatņu izmantošanas</h3>
              <p>
                Pirmo reizi apmeklējot tīmekļvietni uznirstošā logā jums tiks piedāvāts piekrist (poga "piekrītu sīkdatnēm") sīkdatņu izmantošanai, kā arī dota iespēja pielāgot piekrišanu un izvēlēties, kuru no sīkdatņu veidiem jūs vēlaties atslēgt jūsu ierīcē. Visas sīkdatnes, kas nav atzīstamas par obligātām, var tikt izmantotas tikai ar jūsu iepriekšēju piekrišanu. Zobārstniecība vērš uzmanību, ka obligātās sīkdatnes ir nosacījums vietnes izmantošanai, tādējādi to izmantošanai nav nepieciešama piekrišana. Jums ir tiesības nepiekrist šādu statistisku datu veidošanai, uzkrāšanai un apstrādei, jebkurā laikā manuāli atslēdzot sīkdatņu apstrādes mehānisma lietošanu pārlūkprogrammā. Mainīt sīkdatņu iestatījumus vai tās dzēst iespējams interneta pārlūkprogrammas iestatījumos.
              </p>

              <h3 className="text-lg font-serif font-bold text-[#511B29] pt-4">4. Sīkdatņu politikas atjauninājumi</h3>
              <p>
                Tehniski tīmekļvietnes atjauninājumi var notikt ik pa laikam, kā rezultātā var tikt veikti labojumi vai papildinājumi Sīkdatņu politikā. Spēkā esošo Sīkdatņu politikas versiju Zobārstniecība regulāri aktualizē tīmekļvietnē.
              </p>
            </>
          )}
        </div>
      </motion.div>

      {/* Back Button */}
      <div className="mt-10 text-center">
        <Link
          href={langPrefix || '/'}
          className="inline-flex items-center gap-2 text-xs font-bold text-[#6a5b5e] hover:text-[#511B29] transition-colors cursor-pointer"
        >
          <ArrowLeft className="w-4 h-4 text-[#de7c8a]" />
          {isEn ? 'Back to Home' : 'Atpakaļ uz sākumu'}
        </Link>
      </div>
    </motion.div>
  );
}